# Generated by Django 6.0.6 on 2026-07-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_auditor',
            field=models.BooleanField(default=False, help_text='Auditors can review system activity.'),
        ),
    ]
