nginx -> bind domain to a process


server {

    server_name press.weledi.com;

    location / {
        proxy_pass http://unix:/run/weledi-django.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

sudo ln -s /etc/nginx/sites-available/weledi-django  /etc/nginx/sites-enabled